### ISSUE TITLE
Obtain entity manager via @Inject in ItemReader and where else it's needed

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#103]

**Comment by mincong-h** [comment]
The current injection looks like this : 

```java
public class MyItemReader implements ItemReader {

    private EntityManager em;

    @Inject @BatchProperty
    private String persistenceUnitName;

    @Override
    public void open(Serializable checkpoint) throws Exception {
        String path = "java:comp/env/" + persistenceUnitName;
        em = (EntityManager) InitialContext.doLookup(path);
        ...
    }

    ...
}
```

But I'm not sure the JNDI is a good approach and I don't know how to inject the EntityManager via `@Inject` annotation. A question has been posted on SO : [How to inject the EntityManager dynamically?][1].

However, it is not a urgent problem. The above code works for current test cases.

[1]: http://stackoverflow.com/questions/38371744/how-to-inject-the-entitymanager-dynamically

**Comment by gunnarmorling** [comment]
You should be able to use @PersistenceContext.

>

**Comment by mincong-h** [comment]
@gunnarmorling, the `@PersistenceContext` annotation can only provide a static assignment, e.g. "myPU" :

```java
public class MyItemReader implements ItemReader {

    @PersistenceContext(unitName="myPU")
    private EntityManager em;

    ...
}
```

So if user doesn't have the persistence unit called "myPU", or he has multiple PUs, but want to choose another PU among them ?

**Comment by mincong-h** [comment]
After last week's discussion with Emmanuel (issue #112), the idea had been changed : it would be better to inject `EntityManagerFactory` instead of `EntityManager`, so that we can control the lifecycle. So this issue will be marked as _wontfix_ and I close it now.
