### ISSUE TITLE
Inject EntityManagerFactory instead of EntityManager to control the lifecycle

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#112]
In the close method, close the em instead of session.

**Comment by mincong-h** [comment]
According the SO's question : [When to Use EntityManager.clear()?][1], I should add a `em.clear()` before `em.close()` at the end of the batch job, because the answer says

> I see two reasons to clear:

> * when doing batch processing, in order to avoid having a giant cache eating memory and increasing the time to flush because of long dirty checks
> * ...

But the scrollable result is supposed to have no cache, so I need a confirmation from @emmanuelbernard: should I use clear() at the end of the batch job ?

[1]: http://stackoverflow.com/questions/13886608/when-to-use-entitymanager-clear

**Comment by emmanuelbernard** [comment]
No it's useless to do `em.clear()` right before a `em.close()`, it would be redundant.

And I think you use stateless session so you don't need to `clear()` regularly at all.

**Comment by mincong-h** [comment]
OK, thx @emmanuelbernard. I've reverted the code and I'll close it now.
