### ISSUE TITLE
Discuss the TX timeout issue with Sanne

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#113]
MassIndexer uses the TX , how does it solve the timeout ? So today, the JSR352 is not transactional.

See if JSR352 provides fn for TX support .

**Comment by gunnarmorling** [comment]
@mincong-h Could you elaborate a bit what's the problem here?

For sure JSR 352 is using transactions, question is what specifically you mean by "TX support" here. Means of manual TX control in the batch job?

**Comment by mincong-h** [comment]
Hi Gunnar, this issue was created with Emmanuel during our meetup. And it
should concern about :

- For JSR352, the possibility to control the transaction timeout by user
via batch properties or other methods.
- In general, how to prove that we don't have timeout issue for large
dataset ? I met some pb with the aws public dataset (3M rows), but I cannot
reproduce it again ...
- In WF, I increase the timeout in the standalone-test.xml (sth similar),
is that a right way ?
- In Java SE, what should I do ?

Thanks, Gunnar. I'll take a look in the code the noon.

Cheers

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2611
