### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#122]
Copy in index.asciidoc from HS, include batch jsr352

**Comment by mincong-h** [comment]
Why, how to use it ? Core mechanism

**Comment by mincong-h** [comment]
- [ ] The restart mechanism should be detailed, as described in JSR 352 v1.0, page 95

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2612
