### ISSUE TITLE
Write developer reference

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#129]

**Comment by gunnarmorling** [comment]
AsciiDoc preferable over Word doc.

**Comment by mincong-h** [comment]
Hi @gunnarmorling, I added the developer guide, you can check it here : http://mincong-h.github.io/gsoc-hsearch/#developer-guide . It should have many enhancement to do and I'll find some time to do it. Let's discuss it on the next meeting.
