### ISSUE TITLE
Provide a performance test

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#130]
Possibly inspired by existing tests in HSEARCH (if there is any for the mass indexer).

**Comment by mincong-h** [comment]
Performance for indexing 1M people & 100k companies in 10 threads. The performance of these 2 indexers : 

* old massindexer = 31.25s
* new massindexer = 40.77s

**Comment by gunnarmorling** [comment]
Ah, that looks very promising. Is there any way I can run the test myself?

**Comment by mincong-h** [comment]
Hey @gunnarmorling, you can run by checking out the branch `issue-130` then run the command : 

    mvn clean install

BTW, the performance IT is currently part of the wildfly tests in `integrationtest/javaee-wildfly`. I want to split it into another module called `integrationtest/performance`.
