### ISSUE TITLE
Separate simple integration test and performance test

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#139]
There should be a simple integration test which just shows usage on WildFly. The performance test should be separate from that.

**Comment by mincong-h** [comment]
Good idea. Maybe separate them into 2 modules, so that the ignored `RestartIT.java` can be enabled again for the WF usage under module `integrationtest/wildfly` and the `PerformanceIT` can be moved to module `integrationtest/performance` to test the performance.

**Comment by gunnarmorling** [comment]
+1 That sounds reasonable.
