### ISSUE TITLE
Use own version for this project for the time being

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#140]
Re-using the version from Hibernate Search is a bit confusing as long as it's not integrated yet. Something like 1.0.0 should be fine.

**Comment by mincong-h** [comment]
+1. I'll change it to 1.0.0. By the way, can we give a better artifact ID to the project ? It is called `hsearch-jsr352` for instant. I suggest to use `hibernate-search-jsr352` or `hibernate-search-batch`, what do you think ? @gunnarmorling
