### ISSUE TITLE
Provide a synchronous method for the mass indexer

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#144]
Currently, the mass indexer can only be started in an async way. We should add a sync method for it too.

``` java
massIndexer.startAndWait();
```

**Comment by yrodiere** [comment]
`org.hibernate.search.MassIndexer#startAndWait()` already exists. Maybe you could mention which mass indexer your are talking about (the fully qualified class name)?

**Comment by mincong-h** [comment]
Yes, you're right, I should mention the full name. It's [org.hibernate.search.jsr352.BatchIndexingJob.Builder#start()][1], which is part of the code of this repo.

> Why I called it `MassIndexer` previously?

Because this `BatchIndexingJob` was called `MassIndexer` too, and the initial propose of the Google Summer of Code was to refactor the entire mass indexing package. Finally, it might be better to maintain two versions: the existing `MassIndexer` in Hibernate Search and the new version of `BatchIndexingJob`. This renaming was done in issue #151.

[1]: https://github.com/mincong-h/gsoc-hsearch/blob/c15633f0a2912b2cf50531c7742ae37b201d1229/core/src/main/java/org/hibernate/search/jsr352/BatchIndexingJob.java

**Comment by yrodiere** [comment]
I don't think it would be a good idea to provide ways to start the batch job from the Hibernate Search core APIs.

One of the main points of supporting JSR-352 is that the job orchestration APIs are standardized. I'd say anyone who wants to launch a job should use those standardized APIs and nothing else.

Closing for now, feel free to reopen if you think there are compelling reasons to fix this issue.

**Comment by yrodiere** [comment]
Also see #170, which is related.
