### ISSUE TITLE
Allow to select the entities to be re-indexed through a HQL/JPQL query

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#146]
Currently, the selection of entities can only be done through their class type. Selection through a HQL/JPQL query is great to have.

**Comment by mincong-h** [comment]
Now, the index though a HQL query is available:

```java
long executionId = new MassIndexer()
        .addRootEntity( Company.class )
        .hql( "select c from Company c where c.name in ( 'Google', 'Red Hat' )" )
        .start();
```

However, this option is under several conditions:

1. There's not _query validation_ before the job's start. If the query is invalid, then the job will failed to process the partition plan on the 2nd step `produceLuceneDoc`.
2. ⚠️ The partitioning is disabled in this HQL approach. Why? Because allowing the parallel execution requires an ordered-by-entity-ID selection (through criteria or HQL), so that `PartitionMapper` can scroll this selection projected on ID and split it into multiple sub-selections. In each sub-selection, the bounds are limited by the lower bound and the upper bound. However, in HQL approach, the query is given by the user. There's no guarantee for any order.
3. Checkpoint algorithm is disabled. We always start from the very beginning.
4. Restarting a stopped job might create duplicates due to the 3rd point. The solution also depends on the solution of 3rd point.
  1. If it is OK to disable the checkpoint algorithm and always restart from zero, then the solution could be adding a purge in `EntityReader` when HQL approach is detected.
  2. If the checkpoint algorithm is needed. Then we can change `AddLuceneWork` to `UpdateLuceneWork` for HQL approach for a restarted job.

Hi @gunnarmorling & @sanne, any suggestion for the 4 points above?

**Comment by yrodiere** [comment]
1. seems acceptable for now. We may solve it in a later improvement.
2. seems acceptable for now. We may solve it in a later improvement.
3. (and 4) In my opinion the solution would be to use checkpoints, but to also solve #157

So, to sum up, here is what we should do:

1. Fix #157, add checkpoints for the HQL case and test it
2. Create tickets on [JIRA](https://hibernate.atlassian.net/projects/HSEARCH/issues) to remember to fix the remaining issues eventually
3. Document the remaining limitations

**Comment by mincong-h** [comment]
> 1. seems acceptable for now. We may solve it in a later improvement.
> 2. seems acceptable for now. We may solve it in a later improvement.
> 3. (and 4) In my opinion the solution would be to use checkpoints, but to also solve #157

I agree with you on points 1, 2. As for point 3, I'm not sure how to use HQL in checkpoints. The current checkpoint algorithm is based on entity IDs, which uses criteria to define boundaries for each partition. When using HQL, it's very difficult to handle checkpoints because:

- The given HQL might have no order.
- It's impossible add restrictions to HQL.

> So, to sum up, here is what we should do ...

+1

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2613
