### ISSUE TITLE
Enhance monitoring

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#148]
We should find some ways to enhance the index monitoring : via log and UI (JMS ?).

**Comment by gunnarmorling** [comment]
That one I don't quite understand. I'd expect the tools of the environment
(e.g. WildFly) to be used for this. E.g. in the WF console and/or CI the
progress of running jobs should be visible. After all, that's one of the
big advantages of using the standardized API. Or do you have something else
in mind here?

**Comment by mincong-h** [comment]
What I mean is to monitor the indexing progress via some interfaces, maybe not the CLI but from HTML pages. Also, the new mass indexer should have possibility to know the progress for each root entity type, e.g. {"Company.class": "100.0%", "Employee.class": "59.1%"}

The batch runtime supports the following chunk-type step metrics (Spec v1.0, page 85):

1. readCount - the number of items successfully read.
2. writeCount - the number of items successfully written.
3. filterCount - the number of items filtered by ItemProcessor.
4. commitCount - the number of transactions committed.
5. rollbackCount - the number of transactions rolled back.
6. readSkipCount - the number of skippable exceptions thrown by the ItemReader.
7. processSkipCount - the number of skippable exceptions thrown by the ItemProcessor.
8. writeSkipCount - the number of skippable exceptions thrown by the ItemWriter.

But I'm not sure it replies exactly our request of monitoring and the metrics are processed only at the end of the execution with statuses different from STARTED, e.g. COMPLETED, FAILED, STOPPED, ABANDONED.

**Comment by mincong-h** [comment]
After having done the task #134 and #161, the monitoring is now enhanced:

- Show the root entity names separately
- Show indexing progress correctly in both first-start and restart.

```
12:10:03,300 INFO  [org.hibernate.search.jsr352.internal.steps.lucene.ProgressAggregator] (Batch Thread - 1) 

	org.hibernate.search.jsr352.test.entity.Company: 9000/10000 works processed (90.00%).
	org.hibernate.search.jsr352.test.entity.Person: 9000/10000 works processed (90.00%).

12:10:03,361 INFO  [org.hibernate.search.jsr352.internal.steps.lucene.ProgressAggregator] (Batch Thread - 1) 

	org.hibernate.search.jsr352.test.entity.Company: 9000/10000 works processed (90.00%).
	org.hibernate.search.jsr352.test.entity.Person: 9500/10000 works processed (95.00%).

12:10:03,427 INFO  [org.hibernate.search.jsr352.internal.steps.lucene.ProgressAggregator] (Batch Thread - 1) 

	org.hibernate.search.jsr352.test.entity.Company: 9500/10000 works processed (95.00%).
	org.hibernate.search.jsr352.test.entity.Person: 9500/10000 works processed (95.00%).

12:10:03,449 INFO  [org.hibernate.search.jsr352.PerformanceIT] (default task-2) Job execution (id=1) is still working (status=STARTED).
12:10:03,493 INFO  [org.hibernate.search.jsr352.internal.steps.lucene.ProgressAggregator] (Batch Thread - 1) 

	org.hibernate.search.jsr352.test.entity.Company: 9500/10000 works processed (95.00%).
	org.hibernate.search.jsr352.test.entity.Person: 10000/10000 works processed (100.00%).

12:10:03,497 INFO  [org.hibernate.search.jsr352.internal.steps.lucene.ProgressAggregator] (Batch Thread - 1) 

	org.hibernate.search.jsr352.test.entity.Company: 9500/10000 works processed (95.00%).
	org.hibernate.search.jsr352.test.entity.Person: 10000/10000 works processed (100.00%).

12:10:03,512 INFO  [org.hibernate.search.jsr352.internal.steps.lucene.ProgressAggregator] (Batch Thread - 1) 

	org.hibernate.search.jsr352.test.entity.Company: 10000/10000 works processed (100.00%).
	org.hibernate.search.jsr352.test.entity.Person: 10000/10000 works processed (100.00%).
```
