### ISSUE TITLE
Test starting/stopping the job using WildFly tooling (e.g. CLI)

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#150]
Probably more a manual test so we know that this is working

**Comment by mincong-h** [comment]
Hi @gunnarmorling, according to WildFly documentation - [Batch (JSR-352) Subsystem Configuration][1], CLI can be used to start and stop a job from a deployment. However, starting a job from an installed module doesn't seem to possible. I created an issue for it: https://issues.jboss.org/browse/JBERET-263

[1]: https://docs.jboss.org/author/display/WFLY10/Batch+(JSR-352)+Subsystem+Configuration

**Comment by yrodiere** [comment]
From what I can see in https://issues.jboss.org/browse/JBERET-263, the JBeret developers gave useful advice. Maybe in the light of this, we can now implement a test?

Also, maybe the test could simply invoke the CLI?

**Comment by mincong-h** [comment]
First of all, I must admit that I don't remember the detail very well... I did a test manually—generate a war file and then launch it via WildFly CLI, but that one failed. Actually, the CLI can detect the batch job inside the war, but it cannot detect the mass-indexing batch job installed in the Hibernate Search module. Then based on [this comment of this issue][1], I gave up completely.

> Maybe in the light of this, we can now implement a test?

You're right, we should implement a test to understand how it works programmatically, and adapt the useful advice of James, provided in that ticket. Actually I didn't fully understand his explanation.

> Also, maybe the test could simply invoke the CLI?

I don't know how to do it...

[1]: https://issues.jboss.org/browse/JBERET-263?focusedCommentId=13300591&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13300591

**Comment by yrodiere** [comment]
> > Also, maybe the test could simply invoke the CLI?
>
>I don't know how to do it...

It's no big deal, really: http://stackoverflow.com/a/8496537/6692043
The hardest part will be to find what command to execute, and in particular to resolve the location of the Wildfly server on the filesystem.

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2614
