### ISSUE TITLE
Use java.lang.String for all the batch properties

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#152]
In the https://github.com/jberet/jsr352/issues/80, @jamezp mentioned that 

> The batch injections are only required to work on type `java.lang.String`. So [this][1] will work with JBeret but may not work with other batch implementations.

So the idea is to use `java.lang.String` for every batch property. Once injected, then cast them into different types.

[1]: https://github.com/mincong-h/gsoc-hsearch/blob/master/core/src/main/java/org/hibernate/search/jsr352/internal/JobContextSetupListener.java#L37-L39

**Comment by jamezp** [comment]
Unfortunately yes. JBeret will inject different types, but other implementations may not. It's possible you could do something like https://github.com/jberet/jsr352/blob/master/jberet-core/src/main/java/org/jberet/creation/BatchBeanProducer.java for other implementations, but it's likely not worth it.
