### ISSUE TITLE
PartitionMapper should not allow caching

### ISSUE THREAD

**Issue by Sanne** [mincong-h/gsoc-hsearch#154]
Enabling the cache on a large "scroll-all-table" operation is never helpful, but often has undesirable side effects on performance.
Caching should be off by default, and the option to enable caching in this component should not be available.

**Comment by mincong-h** [comment]
Thanks for this note, @Sanne. I'll disable the caching option in partition mapper in this case. However, should caching option be banned for [`EntityReader`'s scrolling][1] too? FYI, in entity reader, the range of entities scrolled is `[lowerID, upperID[`, not the entire table.

[1]: https://github.com/mincong-h/gsoc-hsearch/blob/8b446c0fccb46c0b597a1c2619e075b3aa77b5e4/core/src/main/java/org/hibernate/search/jsr352/internal/steps/lucene/EntityReader.java#L215-L220

**Comment by Sanne** [comment]
For `EntityReader` it's ok. I would still suggest to default to `false`, but having the option can be useful, as when reading actual entities you might be reading a complex graph with relations.

**Comment by mincong-h** [comment]
The default setting has already been set to false. I understand better the meaning of keeping this option now. Thx!
