### ISSUE TITLE
Checkpoints to recover correctly from indexing failure

### ISSUE THREAD

**Issue by Sanne** [mincong-h/gsoc-hsearch#157]
The current integration with the batch Checkpointing feature guarantees to re-read the correct range of entities from the database, but we have a problem when re-writing the list of entities to the index.

The used `LuceneDocWriter` class will forward a payload of type `AddLuceneWork`, which doesn't check for existing entries with the same id like the `UpdateLuceneWork` would do; this might result in:
- duplicate Documents in the lucene document
- failure to delete a Document which has been written in the first attempt, but then deleted before the second attempt (we'd need the clean up the ones which have already been written)

Using `AddLuceneWork` is much more efficient than `UpdateLuceneWork` so switching work type is not desirable; also it doesn't solve the problem with entries having been deleted in parallel.

Lucene might automatically flush in background during the operations, so avoiding the flush until the very end is not a reliable option.

Possible ideas:
- control the flush operation; there should be ways to strictly prevent it from flushing in background as we control the Merging thread; however this could lead to OutOfMemory problems with the Lucene buffers.
- use the Lucene checkpoint API to create a safe checkpoint to return to.

Open limitation of both approaches:
- this batch operation is running in parallel with "live transactions" whose changes should not be thrown away
- if 2 (or more) parallel instances of LuceneDocWriter are forwarding to the same index they should not rollback the work from the other workers. I believe a simple solution to this would be to strictly limit the workers to a single one as it's not doing enough work to warrant parallelism but merely forwarding tasks to the backend.

**Comment by Sanne** [comment]
An alternative solution would be to avoid passing lists of ids among the job steps, but pass the individual tasks.

It just occurred to me that the batching API seems designed to encourage this, as you'd have no problem of partially updated works if your work is atomic.

This might be the simplest solution but requires:
 - to avoid flushing in each write as that would be prohibitive
 - to check that you can fetch N entities with a single query, even though you produce N individual output tasks (I assume this should be possible but I'm not sure).

Not sure if this scales; requires the JBatch implementation to be quite smart but I guess a performance test will tell.

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2616
