### ISSUE TITLE
Refactor the MassIndexer

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#159]
I've asked a question on Code Review about [How to optimize this chained invocation in Java?](http://codereview.stackexchange.com/questions/142697/how-to-optimize-this-chained-invocation-in-java)
## Question

I've a class called `MassIndexer.java` and it uses chained invocation for building a batch job. Each method assigns a property of this job and finally the job will be started using method `MassIndexer#start()`. Here's an example for Java EE:

```
long executionId = new MassIndexer()
        .addRootEntities(Company.class, Employee.class)
        .start();
```

According to different environments, the requirement is different. Some methods are required in Java SE while all of them are optional in Java EE. If users use `MassIndexer` under Java SE and they forget to set the properties through those required methods, the job will fail. These required methods on Java SE are:
- `isJavaSE(boolean)`
- `entityManagerFactory(EntityManagerFactory)`
- `jobOperator(JobOperator)`

Here's another example for Java SE:

```
long executionId = new MassIndexer()
        .addRootEntities(Company.class, Employee.class)
        .isJavaSE(true)
        .entityManagerFactory(emf)
        .jobOperator(jobOperator)
        .start();
```

However, the design of this class in not clear: **people don't know which method is required and which isn't.** The only way to know it is to read the documentation. And I'm wondering how can I improve the design of this class, so that people can easily understand what to do and how to do. For example, should this class be split into `MassIndexerEE` and `MassIndexerSE`? Should it be refactored into a builder class, e.g. `BatchIndexingJobBuilder`?

**And there's no order or logic among these methods.** You can call `foo()` then `bar()`, but `bar()` then `foo()` works too. Properties are used for configurations based on
- selection of class types (about persistence)
- database interaction (about persistence)
- parallel processing (about job)
- checkpoing algorithm (about job)

Someone must be confused when using this class. So I'm searching optimization advices for this class. Every review is welcomed. And you can see the source code of `MassIndexer.java` on [GitHub](https://github.com/mincong-h/gsoc-hsearch/blob/4b8f5525a9ab716618bb42f0b90de0e5d77f5ec9/core/src/main/java/org/hibernate/search/jsr352/MassIndexer.java).
## Actions based on feedback

According to the answers received, here's my action plan for the refactoring:
- [x] Make a second level Builder class `Builder`.
- [x] Avoid using constructor of `MassIndexer`.
- [x] Various arguments of type `Class<?>, Class<?>...` for builder to allow at least 1 argument.
- [x] Rename `MassIndexer` to `BatchIndexing` or something similar (not sure the final name yet). So, we can create the job using `BatchIndexing.Builder(Foo.class)...` or `BatchIndexing.Builder(Foo.class)...`

**Comment by yrodiere** [comment]
@mincong-h Seems like all the actions have been carried on. I'll close this issue, feel free to reopen it if there's still something to do.
