### ISSUE TITLE
Make `BatchIndexingJob.Builder` a *parameters* builder?

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#170]
It seems a bit odd that `BatchIndexingJob.Builder` wraps the call to `jobOperator.start`.

`JobOperator` is part of JSR-352, so there's no reason why users should not be able to do that call themselves.
Also, most of what we're doing in `BatchIndexingJob.Builder` only has to do with building the job parameters (though some parameters are passed through static, global variables for now, see #156).
And finally, the current API prevents users to use additional features of `JobOperator` that should not be our problem at all. For instance, `JobOperator#restart` requires to pass the job parameters. But... We don't expose those parameters. Of course we could expose a `restart` method on the builder, but that's starting to feel like code duplication.

I think our best way out of this situation would be to stop providing a job builder, and simply provide a parameters builder. The builder would return a `Properties` object, and it would be up to the user to start the job.

**Comment by mincong-h** [comment]
Great idea. I agree with you. It will be much clearer for users if we can refactor the builder as you described. 👍 🥇

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2618
