### ISSUE TITLE
Rename the batch indexing job to something more specific to Hibernate Search

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#171]
There are no namespaces for batch indexing job names, so we'd better make sure to use a name that is specific enough.

`BatchIndexingJob` is a bit too generic, I think:

 * another job implementation from another provider that has to do with indexing could have the exact same name
 * users themselves could have a job named like that

Since we provide the name in a static variable anyway, I'd be in favor of making the name a bit more specific, even if it makes it more complex.

Something like "HibernateSearchBatchIndexingJob", maybe?

Also, we should check in the specs or on the web if there are conventions about job naming:

 * Does the name usually include the "batch" and "job" terms (`HibernateSearchBatchIndexingJob`), or is it implied (`HibernateSearchMassIndexing`)?
 * Does the name usually include a package name prefix (`org.hibernate.search.jsr352.MassIndexing`)?
 * Do names usually follow a camelCase formatting, or snake_case, or something else?
 * Are names usually capitalized, or not?

It's something we'll have a hard time changing later, and it won't cost use much to get it right from the start, so I think we'd better work on it now.

**Comment by mincong-h** [comment]
I agree with you that `BatchIndexingJob` is too generic and renaming it is a good idea. Here're some examples that I collected from [JBoss/JBeret][jberet search] and [IBM/JBatch][jbatch search].

GitHub Repo | Job XML | Job ID
:--- | :--- | :---
jberet/jsr352 | `purgeJdbcRepository.xml` | `purgeJdbcRepository`
jberet/jsr352 | `purgeMongoRepository.xml` | `purgeMongoRepository`
jberet/jsr352 | `job-xml-name-different.xml` | `jobXmlNameDifferent`
jberet/jsr352 | `not-restartable.xml` | `not-restartable`
JBatch | `partitionPlanInSplitFlow.xml` | `myJob`
JBatch| `simpleJob.xml` | `runtimejunit.simpleJob`
JBatch | `endOnStep1Failure.xml` | `runtimejunit.stopOnStep1Failure`

[jberet search]: https://github.com/jberet/jsr352/search?l=XML&q=job&utf8=✓
[jbatch search]: https://github.com/WASdev/standards.jsr352.jbatch/search?l=XML&q=job&utf8=✓

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2619
