### ISSUE TITLE
Move files specific to a particular JSR-352 implementation from the main sources to the test sources

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#172]
Some files may be required for testing, but are not directly related to JSR-352 and as such should not be present in the main sources:

 * `/hsearch-jsr352-core/src/main/resources/META-INF/services/org.jberet.spi.JobXmlResolver`
 * `/hsearch-jsr352-core/src/main/resources/META-INF/beans.xml`

**Comment by mincong-h** [comment]
- `/hsearch-jsr352-core/src/main/resources/META-INF/services/org.jberet.spi.JobXmlResolver`

    This file is used to deploy our batch job as a module in WildFly. WildFly will look for SPI's and use those to validate and get the job XML data. Check this email from wildfly-dev: [Deploying JSR 352 job as a module][email].

- `/hsearch-jsr352-core/src/main/resources/META-INF/beans.xml`

    This `beans.xml` is required by JBeret. In case of lack of this file, an exception JBERET000600 will be raised, saying:

    ```
    ERROR: JBERET000007: Failed to run job BatchIndexingJob, , org.jberet.job.model.Job@c1c2d853
    java.lang.IllegalStateException: JBERET000600: Failed to create artifact with ref name jobContextSetupListener.  Ensure CDI beans.xml is present and batch.xml, if any, is configured properly.
    	at org.jberet.runtime.context.JobContextImpl.createArtifact(JobContextImpl.java:185)
    	at org.jberet.runtime.runner.JobExecutionRunner.createJobListeners(JobExecutionRunner.java:136)
    	at org.jberet.runtime.runner.JobExecutionRunner.run(JobExecutionRunner.java:55)
    	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.IllegalStateException: JBERET000600: Failed to create artifact with ref name jobContextSetupListener.  Ensure CDI beans.xml is present and batch.xml, if any, is configured properly.
    	at org.jberet.creation.ArtifactFactoryWrapper.getClassFromBatchXmlOrClassLoader(ArtifactFactoryWrapper.java:65)
    	at org.jberet.creation.ArtifactFactoryWrapper.create(ArtifactFactoryWrapper.java:41)
    	at org.jberet.runtime.context.JobContextImpl.createArtifact(JobContextImpl.java:183)
    	... 6 more
    Caused by: java.lang.ClassNotFoundException: jobContextSetupListener
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	at org.jberet.creation.ArtifactFactoryWrapper.getClassFromBatchXmlOrClassLoader(ArtifactFactoryWrapper.java:63)
    	... 8 more
    ```

[email]: http://lists.jboss.org/pipermail/wildfly-dev/2016-August/005379.html

**Comment by yrodiere** [comment]
> /hsearch-jsr352-core/src/main/resources/META-INF/services/org.jberet.spi.JobXmlResolver
> This file is used to deploy our batch job as a module in WildFly. WildFly will look for SPI's and use those to validate and get the job XML data. Check this email from wildfly-dev: Deploying JSR 352 job as a module.

Right, I didn't make the connection.

Isn't it something that application programmers should do, though? I mean, we chose to provide our job's XML definition through XML in `META-INF`, but what if application programmers want to provide their jobs through other means (in other paths)?

If this service cannot be overridden by users, we definitely should look into it.
Even if it can, I agree this file won't hurt, but it seems a bit weird that *we* configure the user's application. We probably should check whether that's something WildFly expects application programmers to do themselves, by looking in JBeret's documentation for instance. In which case it may be better to add some documentation saying the XML is located in META-INF.

> /hsearch-jsr352-core/src/main/resources/META-INF/beans.xml
> This beans.xml is required by JBeret. 

I believe you, but it's not our problem as a JSR-352 job provider. We shouldn't assume that JBeret will be used, and I think this workaround (since it seems like one: the beans.xml is empty) may equally well be implemented by users that chose to use JBeret. Am I wrong?
Also, I think the `beans.xml` is only needed when using CDI, which we don't want to force users to do (see #86). `beans.xml` will probably become useless once we use fully qualified class names instead of bean names in the job's XML file (if we decide to do that).

**Comment by mincong-h** [comment]
I'm not familiar with these subjects. Maybe we could ask @jamezp, @chengfang?

**Comment by jamezp** [comment]
The answers I'm giving are based on the fact that as I understand this project it is to be installed as a module within WildFly, as well as other containers. My answers will only pertain to WildFly and JBeret though.

With regards to the `org.jberet.spi.JobXmlResolver` service file. I'd argue this should be provided by the library. This is required by WildFly because this is installed via a module and is not part of a deployment. Having the file there is not an issue for other implementations. It allows this project to easily be used in WildFly without the user having to rebuild or modify an existing JAR.

The batch specification requires batch jobs to be located in the `META-INF/batch-jobs` directory. By spec there are no other means to allow for the job XML to be provided. There are ways with WildFly and JBeret, but that is outside of the spec.

Because this is installed as a module the `beans.xml` would be required to activate CDI. The batch specification does require dependency injection. It leaves DI implementation up to the batch implementation. In the case of JBeret that is CDI with Weld as the implementation.

**Comment by yrodiere** [comment]
@jamezp Thanks a lot for your explanations!

@mincong-h So as I understand it, `org.jberet.spi.JobXmlResolver` can stay here as long as users don't go beyond the spec. I'll try to find out whether having this file in our module prevents users to customize the places where JBeret looks for batch job XML files.

As for `beans.xml`, I guess we'll have to see if we manage to solve #86/#156, and how. Depending on that, we'll see whether CDI is used by our module (if it's not, no need for a `beans.xml`), and whether our module requires user to customize some components (if it does, we may have other problems than just a superfluous file).

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2620
