### ISSUE TITLE
Assign more specific names to the beans used inside the job

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#173]
Currently we're naming beans like that:

```
@Named
public class AfterChunkBatchlet extends AbstractBatchlet {
```

Since we don't pass any parameter to `@Named`, it means we use the default name, which appears to be the class name with the first letter lowercased.

Given the really generic names we use for our beans, I'm afraid that in the context of an actual CDI environment we are going to pollute the namespace, and maybe even conflict with other job implementations.

I think we should pass more specific names to the `@Named` annotations. For instance:

```
@Named("hibernateSearchMassIndexingAfterChunkBatchlet")
public class AfterChunkBatchlet extends AbstractBatchlet {
```

**Comment by mincong-h** [comment]
In issue #86, we're trying to replace bean references in the batch job XML file by fully-qualified class names and remove all `@Named` annotations on our bean implementations. This is in progress. So assigning more specific names to the beans is unnecessary. I close the issue. Open it again if using fully-qualified class names cannot be achieved.
