### ISSUE TITLE
Add integration tests using a different JBatch implementation

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#174]
The reference implementation, [JBatch](https://github.com/WASdev/standards.jsr352.jbatch), comes to mind, but also [Spring Batch](http://projects.spring.io/spring-batch/).

We should at least try one of those (preferably JBatch), just to make sure we're not leveraging JBeret-specific features with our current implementation.

I'm a bit worried about the dependency injection in particular, which seems to work surprisingly well even in the JavaSE test...

Note: since `BatchRuntime`, the entry point for JSR-352 implementations, uses java's `ServiceLoader`, we probably can't depend on two JSR-352 implementations at once. I guess we'll have to add some magic to the Maven Failsafe Plugin configuration, use maven profiles, or something.

**Comment by mincong-h** [comment]
I actually started to prepare tests about JBatch, as you can see in my GitHub repo [java-examples][1]. There's also a JBatch sample available [here][2].

[1]: https://github.com/mincong-h/java-examples/tree/master/batch/liberty
[2]: https://github.com/WASdev/sample.batch.bonuspayout

**Comment by yrodiere** [comment]
Cool! Then we won't have to start from nothing: we can build upon this work and integrate it into our project.

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2621
