### ISSUE TITLE
Prepare for integration to the Hibernate Search codebase as a module

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#175]
* Use `hibernate-search-parent` as a parent (and solve the problems it may create?)
 * Remove properties that are already defined in `hibernate-search-parent` (maybe with a slightly different name)
 * Remove dependency management that is redundant with that of `hibernate-search-parent`
 * Remove explicit versions in `<dependencies>` (see `hsearch-jsr352-core` for instance)
 * Rename 'internal' packages to 'impl'
 * Insert a 'massindexing' package between 'jsr352' and its subpackages, so as to be future-proof: we may want to add other jobs in the future.
 * Remove weird empty lines at the beginning of some methods (`StepProgressSetupListener#beforeStep` for instance)

**Comment by yrodiere** [comment]
@mincong-h This issue seems to be the last blocker :) I'll try to work on this this week or next week and create a branch in the Hibernate Search repo (probably mine, because we're quite conservative about exposing transient branches on the main repo). Then we can continue the work on a full Hibernate Search branch with this module.
If you still have work in progress, now's the time to submit a PR!

**Comment by mincong-h** [comment]
> This issue seems to be the last blocker :)

Yes, this is a great news! By the way, thank you for taking so much time on this project and I really appreciate it.

> probably mine, because we're quite conservative about exposing transient branches on the main repo

Using your repo is a good idea, :+1:

> Then we can continue the work on a full Hibernate Search branch with this module.

Actually, I'd like to know how will happen with all the commits? If we push all of them (300+ commits) into the official repo, it might not be a good idea. But I don't know if any good strategy to handle it well. (Squash all of them into one commit or rebase them into several ones?)

> If you still have work in progress, now's the time to submit a PR!

I don't have any work in progress. Actually I'm not in France for the moment. If you think I can help to handle any thing, I can work on it starting from the next Monday (by night).

**Comment by yrodiere** [comment]
> Actually, I'd like to know how will happen with all the commits?
I'll what can be done. I'll first try to squash most commits and apply them on top of the Hibernate Search repo, but if it's too complex I think I'll just copy/paste the code and create one commit on the new repo. I'll edit the metadata so this commit mentions you as the author (if I forget that, then please remind me!)

> I don't have any work in progress.
Good: work on this issue is likely to create conflicts anyway. I'll proceed and keep you updated.

**Comment by mincong-h** [comment]
Issue solved by PR #189. Now we're ready to integrate this repo into Hibernate Search. :grin:
