### ISSUE TITLE
Remove "jobContextData" from the job parameters

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#178]
Using `JobContextData` in the job itself seems sensible, as it avoids to deserialize objects constantly while running the job.

But it is currently extracted from a single job parameters, and the format of this parameter is actually the format of Java object serialization (not easily human-readable). This makes it hard to launch a job from the command-line in WildFly for instance.

We should make sure that job parameters are atomic, i.e. they can't be split into multiple smaller parameters.

**Comment by yrodiere** [comment]
Actually, I just understood that the `jobContextData` in parameters is only used to transfer the criteria (`JobContextData#criterions`).

We should probably:

 * remove the `jobContextData` parameter
 * add a `criteria` parameters instead, which we would expect to be a `Set<Criterion>` serialized using the default Java serialization.
 * remove the implementation of `Serializable` in `JobContextData` (it wouldn't be needed anymore)

The criteria still wouldn't be usable from the command-line, but at least we would avoid mixing `JobContextData` (which is essentially the internal state of an executing job) with job parameters.

**Comment by yrodiere** [comment]
So... I got fooled :) It seems the travis build doens't currently run integration tests, which made me think everything was fine while actually it wasn't.
I'll try to see what's wrong and push a fix.

**Comment by yrodiere** [comment]
Closing: I reached a dead-end. There may not always be a persistence unit, because this is a JPA concept with no equivalent when using native Hibernate APIs, and thus there may not be a persistence unit name...

**Comment by yrodiere** [comment]
Reopening and removing my previous comments: I posted them in the wrong issue. Too many tabs open...

**Comment by mincong-h** [comment]
I agree with you 👍
