### ISSUE TITLE
Add a "tenantId" parameter

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#182]
The current mass indexer in Hibernate Search supports setting the tenant ID, so as to index only part of the database. See `org.hibernate.search.batchindexing.impl.MassIndexerImpl.tenantIdentifier(String)`.
Our batch indexing job should thus accept a "tenantId" parameter and set it on all the created sessions.

**Comment by mincong-h** [comment]
You're right. Actually, @gunnarmorling has already asked me to address to tenant-id task in issue #133, the 9th point in the first comment. Could you explain me a little bit more about how to use tenantId once it is set through the job parameter? Should it be something like:

```java
public class MyBatchComponent {

    @BatchProperty
    private String tenantId;

    public void myMethod() {
        ... = tenantIdentifier(tenantId);
    }
}
```

**Comment by yrodiere** [comment]
@mincong-h I only know the theory, but once the tenant ID is known, and supposing the multi-tenancy has already been configured by the users, it's no big deal, really. Just a matter of retrieving the session correctly:

```
        session = sessionFactory
            .withOptions()
            .tenantIdentifier( tenant )
            .openSession();
```

It requires to use Hibernate-specific (non-JPA) APIs, but in our case we don't care, because Hibernate Search only works with Hibernate ORM.

More information there: https://docs.jboss.org/hibernate//stable/orm/userguide/html_single/Hibernate_User_Guide.html#multitenacy-hibernate

As for the testing environment, we can take some inspiration from existing tests in Hibernate Search, in particular `org.hibernate.search.test.batchindexing.DatabaseMultitenancyTest#shouldBeAbleToRebuildTheIndexForTheTenantId()`.

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2624
