### ISSUE TITLE
Tests should not rely on the execution order

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#184]
In some tests, such as `RestartIT` (WildFly tests) or `PerformanceIT`, we add some data to the database inside a test method, but don't clean it at the end of the test method, and expect the data to be present in the following tests.

This is not a good idea, as a failure in one test could then have an impact on another.

A better way to proceed would be to insert the data before _each_ test, and carefully delete it after each test. That way, tests couldn't have any impact on one another. The JUnit annotations `@Before` and `@After` can be applied to methods in the test class to execute code before and after each test.

Note: we usually don't care about this because we set up the entity manager factory to drop the schema upon closing, but in the case of WildFly tests the same entity manager factory is used for all tests in a test class, so no cleanup is performed between test methods.

**Comment by mincong-h** [comment]
Actually I didn't know that `@Before` and `@After` are called before and after each test. I mixed `@BeforeClass` and `@Before`, `@AfterClass` and `@After`. The difference are `@BeforeClass` runs only once before the entire test fixture while `@Before` runs before each test. More differences can be seen [here][1].

[1]: http://stackoverflow.com/questions/20295578/difference-between-before-beforeclass-beforeeach-and-beforeall

**Comment by yrodiere** [comment]
Fixed in #187 . Closing.
