### ISSUE TITLE
Only the root entity types are supported... ?

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#185]
From the documentation:

```
Please notice that for instant, only the root entity types are accepted. It
should have no relationship between 2 root entities. Because relationships are
not implemented in the framework yet, such as one-to-many, many-to-many.
```

I understand that only root entity types are supported for now. I don't understand why, though?

It's absolutely not the responsibility of the mass indexer to handle relationships, it is the engine's. So why would that have anything to do with this module... ?

**Comment by mincong-h** [comment]
It was my mistake. As you said, it's not the responsibility of the mass indexer to handle the relationship, but it is the engine's. Gunnar had explained it, but I never updated the documentation. Actually, the documentation has never been reviewed / updated. So you might find many out-of-date information in the doc...

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2626
