### ISSUE TITLE
Use a proper JBoss Logger to log and to throw exceptions

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#188]
See `org.hibernate.search.util.logging.impl.Log` and its uses.

**Comment by mincong-h** [comment]
Thanks @yrodiere, I'll take a look this weekend.

**Comment by yrodiere** [comment]
@mincong-h If you can, it'd be great :) But maybe you should wait for the code to be integrated into the Hibernate Search codebase: I'm currently doing some package refactorings that will make it hard to handle conflicts: see #189

**Comment by mincong-h** [comment]
Yes you're right, then I will do it later :)

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2627
