### ISSUE TITLE
Separate test entities and actual batch classes

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#37]
The actual batch implementation should be under `src/main/java`, while the test entity and related test classes should be under `src/test/java`. That way we'll properly separate "framework"/"library" code from testing code.

**Comment by gunnarmorling** [comment]
Tests should be run using Arquillian then.

**Comment by gunnarmorling** [comment]
Also the resources for testing (RHT test data file) should go to src/test/resources.

**Comment by mincong-h** [comment]
Classes have been separated. I close the issue now.
