### ISSUE TITLE
Remove yahoo-finance-RHT.csv

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#38]
Seems not needed?

**Comment by mincong-h** [comment]
I've created a second table `stock` in my database. This CSV file is used to provide data for such table. Maybe I should move it to Google Drive or Drop Box.

**Comment by gunnarmorling** [comment]
Ok, I was just confused by the name of the project ("us-address") and
seeing this file there. If both are needed for tests, that's fine. Just
rename the project then as suggested in that other issue.
