### ISSUE TITLE
Evaluate performance and improve it to be similar to that of org.hibernate.search.MassIndexer

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#4]
Why JSR 352 can increase performance, comparing to the current mass indexer ? This issue aims to list all the pros for the JSR 352 related to the performance and finally give a support for the Google Summer of Code's report. The final result will be posted to project's wiki.

**Comment by mincong-h** [comment]
What about the performance of the new implementation ? Let's say, for indexing 3221316 entities in the database `addresses`.

**Comment by mincong-h** [comment]
_Had the cache been ignored ?_

**Comment by mincong-h** [comment]
In issue #130, I said that 

>Performance for indexing 1M people & 100k companies in 10 threads. The performance of these 2 indexers :

> * old massindexer = 31.25s
> * new massindexer = 40.77s

We should continue to work on it and improve its performance.

**Comment by gunnarmorling** [comment]
+1. Eventually there should be no significant difference to the existing
one (it can be faster of course :).

**Comment by yrodiere** [comment]
Closing; moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2609
