### ISSUE TITLE
Create a JBoss Modules module for the batch job

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#44]
Eventually, the batch job should not be part of a WAR but rather a module for the JBoss Modules system (on which WildFly is based on). To do:

* Create a "Module ZIP" file akin to the one in Hibernate Search: https://github.com/hibernate/hibernate-search/tree/master/modules; It should contain a single module for the Search batch job, with the right module.xml
* Unzip that module zip into the "modules" directory of the WildFly used for testing as part of the integration tests

**Comment by gunnarmorling** [comment]
I can help with that once we get there.

**Comment by mincong-h** [comment]
This issue is duplicate with issue #132. Close it now.
