### ISSUE TITLE
Fetch WildFly for testing via maven-dependency-plugin

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#45]
https://github.com/hibernate/hibernate-search/blob/master/integrationtest/wildfly/pom.xml#L273...L320

**Comment by mincong-h** [comment]
Hi @gunnarmorling 

I saw the below codes in the above link : 

```xml
<artifactItem>
  <groupId>org.hibernate</groupId>
  <artifactId>hibernate-search-modules</artifactId>
  <version>${project.version}</version>
  <classifier>wildfly-10-dist</classifier>
  <type>zip</type>
  <overWrite>true</overWrite>
  <outputDirectory>${project.build.directory}/node1/wildfly-${wildflyVersion}/modules</outputDirectory>
</artifactItem>
```

And I've 2 questions :

1.  Does it mean that : 

    The current project packages as artifact `hibernate-search-modules` using dynamic version provided by pom embedded variables `project.version`. The artifact's type is zip. Once the package is created, it will be placed in the output directory `${project.build.directory}/node1/wildfly-${wildflyVersion}/modules` as a module. Overwrite the existing one if exists. So this artifact replaces the default `hibernate-search-modules` module included in the wildfly-10-dist (node1), and becomes the chosen one.

2.  What does `<classifier>` mean ?

**Comment by gunnarmorling** [comment]
Hey,

> Does it mean that [...]

Essentially yes. Only that the HSEARCH modules from the ZIP are added *next
to* the exiting ones, with a different version (named "slot" in WildFly
terminology). Then in the integration test the slot of the HSEARCH module
to use is given my means of a property. I recommend you ask on
hibernate-dev if you have more questions on this (@Sanne can give you more
details about that test setup used in HSEARCH)

> What does <classifier> mean

It's just another part of the Maven artifact coordinates (besides group id,
artifact id and version). It allows to distinguish two related artifacts
which are meant for different environments typically. E.g. there could be
another one with qualifier "wildfly-9" (for updating HSearch in WF 9).
Other examples are artifacts which are specific to a version of the JDK
(e.g. classifier "jdk-8").

**Comment by mincong-h** [comment]
> Does it mean that [...]

It is a brilliant idea. Comparing to the replacement, using multiple slots gives developers the flexibility to choose the appropriate slot according to situations. That's cool 😎 !! Your answer is very clear so that's enough for me. I'll use the ML if needed.

> What does <classifier> mean

OK for this. 

Thanks Gunnar !

**Comment by mincong-h** [comment]
Done in commit 4884f46.
