### ISSUE TITLE
Think about split of public API and internal implementation packages

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#48]
Most of the classes of the batch are not meant for direct usage by the user (if not even all). They should live under an `internal` package as done in Hibernate Search.

**Comment by mincong-h** [comment]
Here's an overview of changes : 

1.  **Internal**. All classes belonging to package `io.github.mincongh.batch` have been moved to `org.hibernate.search.jsr352.internal`.
2.  **public API**. A public class `MassIndexer` has been added to `org.hibernate.search.jsr352`. It is similar to the implementation class of the current indexer `MassIndexerImpl` and similar to the `io.github.mincongh.session.BatchSession`. 

_TODO list_

- [ ] Discussion: should the classes internal be separated into sub package(s) ? 
- [ ] Separate the class `MassIndexer` into interface `MassIndexer` and implementation `MassIndexerImpl`. This will be probably done in other issue
