### ISSUE TITLE
Use logger instead of System.out.println

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#49]
Use JBoss Logging for the purposes of logging info for debugging/tracing. The set-up can be taken from the other Hibernate projects.

**Comment by mincong-h** [comment]
Classes located in package `io.github.mincongh.session` and `io.github.mincongh.servlet` haven't been changed because they'll be deleted one day. Classes located in packages `org.hibernate.search` have been changed.
