### ISSUE TITLE
Persistence unit as RESOURCE_LOCAL or JTA?

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#51]
Currently, the JTA is used. However, if the project is runtime independent, then maybe RESOURCE_LOCAL is a better choice ? Otherwise user need to configure their runtime e.g. WF10 for running tests. Am I right ?

Ref : [Persistence unit as RESOURCE_LOCAL or JTA?][1]

[1]: http://stackoverflow.com/questions/1962525/persistence-unit-as-resource-local-or-jta

**Comment by mincong-h** [comment]
I think RESOURCE_LOCAL might be a better choice. Because there's only one application in our test container(s). And RESOURCE_LOCAL can be applied to both Java SE and Java EE. Currently, 

*  Java SE tests use LOCAL_RESOURCE with H2
*  Java EE tests use JTA with MySQL

I might change them all into LOCAL_RESOURCE, @gunnarmorling any idea ? However, this is really a minor issue.

**Comment by mincong-h** [comment]
Currently, I use LOCAL_RESOURCE mode in Java SE tests and JTA mode in Java EE tests. However, I need to clarify that the initial propose of this issue is wrong: 

The job `mass-index` does not choose its own mode of persistence unit. It doesn't contain persistence unit. The mass indexing is done with PU provided by the user, so it works in both modes.

**Comment by gunnarmorling** [comment]
Your final summary sounds reasonable :)

**Comment by mincong-h** [comment]
Thanks @gunnarmorling, GSoC is really a good place for learning new stuff.
