### ISSUE TITLE
Cannot find indexed results after mass index

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#78]
Hi @gunnarmorling , you're absolutely right about the test : I need to find the indexed results after mass indexing. I thought that it is evident, but you're right again : it isn't.

## directory provider = filesystem

When directory provider is in mode _filesystem_, the lucene files have been created, but when I searched the result, it returns 0 results. It need to wait until next start of the server WF to return result. 

For example : 

### Should be

1. Launch command `mvn clean install`
   1. Search results having keyword `google` before index, expected 0 row found.
   2. Mass index.
   3. Search again, expected 1 rows found.

### Reality

1.  Launch command `mvn clean install`
   1. Search results having keyword `google` before index, expected 0 row found.
   2. Mass index.
   3. Search again, expected 1 rows found. **But 0 row found**.
2.  Launch command `mvn clean install` again. (in directory provider = `filesystem`, those lucene files still exist)
   1. Search results having keyword `google` before index, expected 0 row found. **But 1 rows found.**

Before jumping into the code, does it mean anything to you? 

The production of lucene work is located and only located at [BatchItemProcessor.java][1].

## directory provider = ram

After that, I've also tried the in-memory mode. However, I need to resolve the above bug first, because in _ram_ mode, the lucene files are stored in memory and might be destroyed after the maven build, I cann't reproduce the above situation in that case.

[1]: https://github.com/mincong-h/gsoc-hsearch/blob/accf7e1660feaa1b1d49dce383b95f77b85c2ab0/core/src/main/java/org/hibernate/search/jsr352/internal/BatchItemProcessor.java#L159-L204

**Comment by mincong-h** [comment]
This error can be reproduced by following the below steps : 

1. Checkout the branch _[issue-78][1]_.
2. In project home directory, use `mvn clean install`
3. In project home directory, use `mvn clean install` again

The error of the first install will be : 

> Results :
>
>Failed tests: 
>  [MassIndexerIT.testJob:163][163] expected:<1> but was:<0>
>
>Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

The error of the second install will be : 

> Results :
>
>Failed tests: 
>  [MassIndexerIT.testJob:119][119] expected:<0> but was:<1>
>
>Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

This demonstrates that my implementation can index entities, but the indexed results are only available in the 2nd launch, which is very weird. 

[1]: https://github.com/mincong-h/gsoc-hsearch/tree/issue-78
[119]: https://github.com/mincong-h/gsoc-hsearch/blob/issue-78/integrationtest/javaee-wildfly/src/test/java/org/hibernate/search/jsr352/MassIndexerIT.java#L119
[163]: https://github.com/mincong-h/gsoc-hsearch/blob/issue-78/integrationtest/javaee-wildfly/src/test/java/org/hibernate/search/jsr352/MassIndexerIT.java#L163

**Comment by gunnarmorling** [comment]
@mincong-h I think I figured what's missing. I'll send a pull request shortly.

**Comment by mincong-h** [comment]
Great news, thanks @gunnarmorling

**Comment by gunnarmorling** [comment]
The issue was that a final flush call was missing. I've added this as part of the PR I just sent by means of a batch listener. That's ok for now, but I think eventually the flush should happen after each execution of the entity indexing chunk.

**Comment by mincong-h** [comment]
> but I think eventually the flush should happen after each execution of the entity indexing chunk.

The interface [`ItemWriterListener`][1] can cover this. It has a method `#afterWrite(List<Object>)`. I'll take care of it.

[1]: https://docs.oracle.com/javaee/7/api/javax/batch/api/chunk/listener/ItemWriteListener.html

**Comment by mincong-h** [comment]
The flush can be done in the `ItemWriter#writeItems(List<Object>)` directly.

**Comment by mincong-h** [comment]
This issue is done now. Many thanks for the help of @gunnarmorling, the best mentor in the world  :grin::grin::grin:
