### ISSUE TITLE
Apply code style from Hibernate Search

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#87]
See https://github.com/hibernate/hibernate-search/tree/master/build-config and the configuration of the Maven CheckStyle plug-in in Hibernate Search.

**Comment by gunnarmorling** [comment]
This also includes the addition of the standard file header we use, mentioning the license of the code.

**Comment by mincong-h** [comment]
I don't like much the code style of JBoss :joy:, especially the empty space after parentheses, that's why I didn't do it. But yes, I'll add it for the next week.

**Comment by gunnarmorling** [comment]
Took me a while to get used to it, too. But it's a big advantage if
everyone works with consistent code style settings, so let's re-use the
existing one. You'll like it soon :)

**Comment by mincong-h** [comment]
Done.
