### ISSUE TITLE
Add test for indexing several entity types

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#89]
We should have test that everything works when indexing several entity types. Specifically I'm concerned about the index sharding strategy stored in `IndexingContext` which is a singleton.

**Comment by mincong-h** [comment]
There're 2 entity types that have been added in these days. They're `Person.class` & `MyDate.class`. The class `Person` uses string as primary key and the class `MyDate` use embedded & composited primary key, which is (year, month, day).

TODO :

- [ ] Add restart IT for theses classes. Make user the checkpoint position is correct and complex PKs are correctly ordered.

**Comment by mincong-h** [comment]
This task had been done.
