### ISSUE TITLE
Make IndexingContext part of the JobContext

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#92]
Instead of a - container-wide - singleton, the `IndexingContext` should be propagated as transient data in the job context.

**Comment by gunnarmorling** [comment]
I'll add a commit for this to my pending PR #95.

**Comment by mincong-h** [comment]
Hi @gunnarmorling , currently only `EntityManager` is still stored in [`IndexingContext`][1], other attributed have been moved into "standardized" classes. Do you know how to avoid the storage of `EntityManager` ? Once done, I can delete this class.

[1]: https://github.com/mincong-h/gsoc-hsearch/blob/22d67b65e42589d55256ecd470e299233cef47d0/core/src/main/java/org/hibernate/search/jsr352/internal/IndexingContext.java

**Comment by mincong-h** [comment]
done.
