### ISSUE TITLE
Avoid usage of Class#forName()

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#93]
It will give use head-aches when providing the batch job as a WildFly module rather than part of the application deployment.

**Comment by gunnarmorling** [comment]
I'll send a fix with my other changes.

**Comment by mincong-h** [comment]
@gunnarmorling, I'm not completely understand your sentence. Do your mean the `Class#forName(String)` search the input name in WF module instead of the app deployment. So it might brings potentially risks to the job ?

**Comment by gunnarmorling** [comment]
Yes, it will be more difficult to load classes by names in the modularized environment of the application server. So better to simply avoid it :)
