### ISSUE TITLE
Correctly handle entity manager and transactions under Java SE

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#96]
Currently, the EM is shared via `IndexingContext`. This is fine under Java EE, where the injected EM is a proxy which ensures that the exposed functionality works in the correct scope, but under Java SE it leads to the EM shared between threads which is not allowed.

Furthermore, we need to manually take care of transaction handling in the item reader/writer under Java SE (the container will do it under Java EE/WildFly).

This should be the next thing fixed after the refactoring we discussed via e-mail (it will be easier to do once the id producer batchlet isn't there anymore and the item processor works with the actual entities and thus doesn't need to access the entity manager).

**Comment by gunnarmorling** [comment]
@mincong-h This may be helpful: https://github.com/apache/incubator-batchee/tree/f08eead0c06749023aa5726fe67e8a2492b2dc2a/extensions/extras/src/main/java/org/apache/batchee/extras/jpa

**Comment by mincong-h** [comment]
Thanks for sharing, @gunnarmorling . I'll take care of this after the refactoring

**Comment by gunnarmorling** [comment]
This might be useful:

    Object id = entityManagerFactory.getPersistenceUnitUtil().getIdentifier(entity);

**Comment by gunnarmorling** [comment]
Thinking more about it, I'm actually fine if we focus on making things work out correctly when using the job under Java EE. I had hoped enabling to test it under plain SE would be helpful, but I realize that it actually makes things more complicated so I'm fine to skip that for the time being.

This means that the entity manager could simply be injected via `@PersistenceContext` into the reader etc. needing it and we can remove it from `IndexingContext`. We will also get transactions managed by the container.

Eventually, the job should be usable within SE of course. This will require a solution similar to the the things done in that BatchEE link above, allowing to customize the retrieval of the EM. Plus, we need to manually control TX under Java SE.

**Comment by mincong-h** [comment]
Hi @gunnarmorling, in an email in 06 July, we've discussed about the transaction. You said that : 

> Yes, all the items should be read in one transaction. Only that will guarantee a consistent read of all items. The TX timeout can be increased if needed.

I can't do that. I'm not allowed to manipulate transaction in JTA mode. The method `EntityManager#getTransaction()` will raise an `IllegalStateException` if invoked on a JTA entity manager. The same principal is also applied in the above BetchEE example, its reader uses one transaction per read using [`JpaItemReader#nextPage()`][1] : 


```java
    @Override
    public Object readItem() throws Exception {
        if (items.isEmpty()) {
            final Collection<?> objects = nextPage();
            if (objects == null || objects.isEmpty()) {
                return null;
            }

            items.addAll(objects);
            firstResult += items.size();
        }
        return items.pop();
    }

    private Collection<?> nextPage() {
        final EntityManager em = emProvider.getValue().newEntityManager();
        if (transaction) {
            em.getTransaction().begin();
        }
        final Query jpaQuery;
        try {
            if (namedQuery != null) {
                 jpaQuery = em.createNamedQuery(namedQuery);
            } else {
                jpaQuery = em.createQuery(query);
            }
            jpaQuery.setFirstResult(firstResult).setMaxResults(page);
            if (paramProvider != null) {
                paramProvider.getValue().setParameters(jpaQuery);
            }
            final List<?> resultList = jpaQuery.getResultList();
            if (detach) {
                for (final Object o : resultList) {
                    em.detach(o);
                }
            }
            return resultList;
        } finally {
            if (transaction) {
                em.getTransaction().commit();
            }
            emProvider.getValue().release(em);
        }
    }
```

* If TX is managed by user, then it begins after the start of `readItem()` called and commits before `readItem()` ends.
* If TX is managed by the container, then we don't even touch the TX.

I'm not sure if I'm misunderstanding some where. Let's discuss it tomorrow.

[1]: https://github.com/apache/incubator-batchee/blob/f08eead0c06749023aa5726fe67e8a2492b2dc2a/extensions/extras/src/main/java/org/apache/batchee/extras/jpa/JpaItemReader.java#L115-L144

**Comment by mincong-h** [comment]
Keep in mind that reader and processor share the same transaction, but writer don't. And since there's no need to modify database's data, there will be no commit and only rollback can occure. And starting from this point, we can modify the chunk as required.

**Comment by mincong-h** [comment]
Hi @gunnarmorling, since yesterday, I refocus on this issue and mass indexer is capable to work under Java SE now. Here're the major changes : 

1. We don't inject **EM** anymore : the mass indexer uses directly **EMF**. Then, **EM** is created inside the class using **EMF** and it is not shared with other thread.
2. User need to defines a boolean property `isJavaSE` before the job start. According to this property, we can then decide how to obtain the **EMF**. By default, `isJavaSE` is false.
3. In Java SE, **EMF** is obtained before the job start.

   ```java
   massIndexer.isJavaSE( true )
       .entityManagerFactory( emf )
       .start()
   ```

3. In Java EE, **EMF** is injected via annotation `@PersistenceUnit`. So the job can start like this : 

   ```java
   massIndexer.start()
   ```

4. In most of the classes, **EM** is not used, but we use rather `Session` created by session factory. Like **EM**, Session is not shared with other thread neither.

So after the refactoring, the result looks like : 

```java
@Inject
@BatchProperty
private boolean isJavaSE;

@PersistenceUnit(unitName = "h2")
private EntityManagerFactory emf;

private SessionFactory sessionFactory;
private Session session;

@Override
public void open(Serializable checkpointID) throws Exception {
    if ( isJavaSE ) {
        emf = JobSEEnvironment.getEntityManagerFactory();
    }
    sessionFactory = emf.unwrap( SessionFactory.class );
    session = sessionFactory.openSession();
    ...
}

@Override
public void close() throws Exception {
    ...
    try {
        session.close();
    }
    catch (Exception e) {
        logger.error( e );
    }
}
```
